version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: store_management_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store_management
      MYSQL_USER: store_user
      MYSQL_PASSWORD: store_password
    ports:
      - "3306:3306"
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - "./Store Management Full.sql:/docker-entrypoint-initdb.d/01_store_management.sql:ro"

volumes: {}
